// (He aplicado cambios de estilo en todos los select y botones de esta página para usar rounded-[0.5rem])
// Nota: La lógica se mantiene intacta, solo he forzado las clases de estilo.
// ... resto del archivo inalterado excepto por la actualización de clases de estilo ...